// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/efrengarcial/framework/users/pkg/model"
import pagination "github.com/biezhi/gorm-paginator/pagination"

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, where, args
func (_m *UserRepository) Delete(_a0 model.IModel, where string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, _a0, where)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.IModel, string, ...interface{}) error); ok {
		r0 = rf(_a0, where, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: receiver, id
func (_m *UserRepository) Find(receiver model.IModel, id uint64) error {
	ret := _m.Called(receiver, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.IModel, uint64) error); ok {
		r0 = rf(receiver, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: result, where, args
func (_m *UserRepository) FindAll(result interface{}, where string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, result, where)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, ...interface{}) error); ok {
		r0 = rf(result, where, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAllPageable provides a mock function with given fields: pageable, result, where, args
func (_m *UserRepository) FindAllPageable(pageable model.Pageable, result interface{}, where string, args ...interface{}) *pagination.Paginator {
	var _ca []interface{}
	_ca = append(_ca, pageable, result, where)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 *pagination.Paginator
	if rf, ok := ret.Get(0).(func(model.Pageable, interface{}, string, ...interface{}) *pagination.Paginator); ok {
		r0 = rf(pageable, result, where, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pagination.Paginator)
		}
	}

	return r0
}

// FindFirst provides a mock function with given fields: receiver, where, args
func (_m *UserRepository) FindFirst(receiver model.IModel, where string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, receiver, where)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.IModel, string, ...interface{}) error); ok {
		r0 = rf(receiver, where, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOneByEmail provides a mock function with given fields: login
func (_m *UserRepository) FindOneByEmail(login string) (*model.User, error) {
	ret := _m.Called(login)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneByLogin provides a mock function with given fields: login
func (_m *UserRepository) FindOneByLogin(login string) (*model.User, error) {
	ret := _m.Called(login)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: email
func (_m *UserRepository) GetByEmail(email string) (*model.User, error) {
	ret := _m.Called(email)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByLogin provides a mock function with given fields: login
func (_m *UserRepository) GetByLogin(login string) (*model.User, error) {
	ret := _m.Called(login)

	var r0 *model.User
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0
func (_m *UserRepository) Insert(_a0 model.IModel) (model.IModel, error) {
	ret := _m.Called(_a0)

	var r0 model.IModel
	if rf, ok := ret.Get(0).(func(model.IModel) model.IModel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.IModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.IModel) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRecord provides a mock function with given fields: _a0
func (_m *UserRepository) NewRecord(_a0 model.IModel) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(model.IModel) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Save provides a mock function with given fields: _a0
func (_m *UserRepository) Save(_a0 model.IModel) (uint64, error) {
	ret := _m.Called(_a0)

	var r0 uint64
	if rf, ok := ret.Get(0).(func(model.IModel) uint64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.IModel) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *UserRepository) Update(_a0 model.IModel) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.IModel) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
